Distingue le montant à terme de la DSR
leximpact/leximpact-client pull request #85
Opened 2020-08-24 13:58 UTC by LoicPoullain

Trello : https://trello.com/c/2p5lbwQX/397-ajouter-le-montant-de-lann%C3%A9e-prochaine-de-la-dsr

Comme la partie serveur n'est pas implémentée, on ne voit donc rien :
![Capture d’écran 2020-08-24 à 15 18 47](https://user-images.githubusercontent.com/13604533/91053074-9a496800-e622-11ea-90ae-c55bb3f0431d.png)

2020-08-24 14:00 UTC, LoicPoullain commented
La date "à terme" peut être différente pour le PLF ou l'amendement. Si on veut l'afficher, voilà ce que cela donne :

*Cas où les deux dates sont différentes*
![Capture d’écran 2020-08-24 à 15 47 32](https://user-images.githubusercontent.com/13604533/91053274-ded50380-e622-11ea-9ecd-2ea79d470a16.png)

*Cas où la date d'arrivée de l'amendement est identique à celle du PLF*
![Capture d’écran 2020-08-24 à 15 48 12](https://user-images.githubusercontent.com/13604533/91053279-e0063080-e622-11ea-8f29-c6e32cd8a0ba.png)

2020-08-24 14:04 UTC, LoicPoullain commented
Je trouve cela un peu (surchargé), je te propose donc @DorineLam de conserver ta maquette initiale en prenant en compte, comme date, la date la plus éloignée des deux pour que le résultat soit toujours juste. C'est ce qui est implémentée pour l'instant.
![Capture d’écran 2020-08-24 à 15 50 38](https://user-images.githubusercontent.com/13604533/91053525-3a9f8c80-e623-11ea-8558-bea78f197e8e.png)

2020-09-07 07:28 UTC, DorineLam requested changes
@LoicPoullain ce n'est effectivement pas optimal de donner une date si elle n'est pas juste pour tous les montants ; je comprends le cheminement de pensée que tu décris. Je me demande si il n'y a pas une troisième solution : 

- Remplacer "Point d'arrivée en NNNN" par "Montant à terme" ;
- Mettre un tooltip sur les montants avec la date.
- Éventuellement ajouter "en 2021" sur le premier montant.

2020-09-07 08:50 UTC, DorineLam approved these changes

2020-09-07 08:51 UTC, merged