Intégrer la DF
leximpact/leximpact-client pull request #87
Opened 2020-08-31 13:40 UTC by LoicPoullain

Cette PR affiche la DF avec `?df`.

Comme le serveur ne renvoie pas encore de données, les données utilisées sont celle de la DSR.

2020-09-14 16:46 UTC, sandcha commented
@DorineLam Ce sera cette PR bientôt.

2020-09-15 08:02 UTC, LoicPoullain commented
Note à moi-même : avant de fusionner, mettre les résultats DF à 0 (et non égaux la DSR) pour ne pas avoir des "tendances" incorrectes (DSR compté en double)

2020-09-15 08:16 UTC, LoicPoullain commented
@DorineLam : demande de revue.

2020-09-16 17:30 UTC, DorineLam requested changes
@LoicPoullain je sais pas si c'est déjà le moment de merger cette PR ... Mes remarques ci-desous : 

- La DF doit être après la DSU.
- Voir ce qu'on affichera comme textes de loi. La partie répartition va disparaître. ou au moins être cachée. La partie sur les règles de péréquation sera-t'elle modifiable ? Tout ça va influencer ce qu'on présente.

En option : mettre en forme les montants. En les remontant en haut. On en avait parlé avec captures d'écran il me semble. Je ne retrouve pas la carte trello, ça devait être dans Github.

2020-09-24 12:33 UTC, DorineLam commented
@LoicPoullain proposition de modifs du texte de loi pour rendre plus clair qu'on parle uniquement l'écrêtement et pour rendre plus accessible le texte : 

<img width="543" alt="Capture d’écran 2020-09-24 à 14 25 39 4" src="https://user-images.githubusercontent.com/46896006/94145395-c7cc4000-fe72-11ea-8342-da9885d57dea.png">

2020-09-30 12:43 UTC, sandcha commented
@LoicPoullain, Au cas où, au lancement du client, il y a déjà une valeur d'amendement dans la zone impact.
Je vois ceci en première ligne du tableau des strates sans avoir défini d'amendement : 
<img width="637" alt="Screen Shot 2020-09-30 at 14 37 36" src="https://user-images.githubusercontent.com/6567910/94686215-cdba9900-032a-11eb-989a-80cfc145d3f2.png">

Testé en local avec cette PR client et la PR leximpact/leximpact-server#37.
 
> Par ailleurs, tu indiques que les valeurs en dur sont celles de la DSR mais cela semble différent.

2020-09-30 12:52 UTC, LoicPoullain commented
@sandcha ça devrait pas arriver. Je regarde ça.

2020-09-30 13:22 UTC, LoicPoullain commented
@sandcha c'est corrigé. Les valeurs utilisées par défaut étaient celles de la DSR.

2020-10-01 08:58 UTC, DorineLam approved these changes
👍

2020-10-01 08:59 UTC, merged