Activer les montants
leximpact/leximpact-client pull request #90
Opened 2020-09-07 12:15 UTC by LoicPoullain

2020-09-07 13:09 UTC, DorineLam requested changes
L'interface initiale n'est pas la bonne : je dois pouvoir ajouter la maj/min de 2021, et non pas la supprimer ou modifier (car elle n'existe pas) : 
Écran initial de cette PR : 
<img width="693" alt="Capture d’écran 2020-09-07 à 15 05 52" src="https://user-images.githubusercontent.com/46896006/92390730-bddcda00-f11b-11ea-9b00-839b1737dce9.png">

Écran initial souhaité :
<img width="618" alt="Capture d’écran 2020-09-07 à 15 06 57" src="https://user-images.githubusercontent.com/46896006/92390776-d51bc780-f11b-11ea-8f6d-9c1875558769.png">

2020-09-07 13:09 UTC, DorineLam commented
@LoicPoullain quand je fais une augmentation de 90 millions d'euros pour la DSR et la DSU, il n'y a pas de changement dans les résultats ... 🤔

2020-09-07 13:39 UTC, DorineLam commented
@sandcha @LoicPoullain @magemax  le problème est assez visible ici : 
Je viens de supprimer l'augmentation de 90millions faite par défaut, et voici que j'ai une différence dans les résultats.
C'est un contre sens pour l'utilisateur qui n'a pas fait une minoration, à son sens, il n'a juste pas fait de majoration et les résultats devraient donc être identiques : 



<img width="1736" alt="Capture d’écran 2020-09-07 à 15 24 35" src="https://user-images.githubusercontent.com/46896006/92392353-6c821a00-f11e-11ea-9e72-28cc423f4afe.png">

2020-09-09 12:54 UTC, sandcha approved these changes
Merci @LoicPoullain 🙌 
> Les montants sont bien affichés par défaut et avec le serveur en production (moteur ofdl v0.6.0), on ne visualise désormais plus de changement en cas d'estimation sans ajout d'augmentation.

@DorineLam Il me semble qu'on pourrait mettre au pluriel le titre de premier niveau `MONTANT DES DOTATIONS` > `MONTANTS DES DOTATIONS` puisqu'il traite de deux montants et que c'est au pluriel dans le titre de niveau 2 juste en-dessous. Qu'en dis-tu ?

2020-09-09 13:36 UTC, merged

2020-09-09 13:47 UTC, DorineLam commented
@sandcha effectivement montants avec un S => bien mieux !